In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("basilb2s/language-detection")

print("Path to dataset files:", path)

c:\Users\pgrantdetorres\Personal_Development_Projects\ML Engineering\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 542k/542k [00:00<00:00, 1.78MB/s]

Extracting files...
Path to dataset files: C:\Users\pgrantdetorres\.cache\kagglehub\datasets\basilb2s\language-detection\versions\1


In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import pickle

import warnings
warnings.simplefilter("ignore")

In [3]:
import sklearn
print(sklearn.__version__)

1.7.2


In [4]:
data = pd.read_csv("..\data\Language Detection.csv")

In [5]:
data.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [6]:
data['Language'].value_counts()

Language
English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: count, dtype: int64

In [7]:
X = data['Text']
y = data["Language"]

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
le.classes_

array(['Arabic', 'Danish', 'Dutch', 'English', 'French', 'German',
       'Greek', 'Hindi', 'Italian', 'Kannada', 'Malayalam', 'Portugeese',
       'Russian', 'Spanish', 'Sweedish', 'Tamil', 'Turkish'], dtype=object)

In [10]:
data_list = []
for text in X:
    text = re.sub(r'[!@#$(),\n"%^*?\:;~`0-9]',' ', text)
    text = re.sub(r'[[]]', ' ', text)
    text = text.lower()
    data_list.append(text)

In [11]:
X

0         Nature, in the broadest sense, is the natural...
1        "Nature" can refer to the phenomena of the phy...
2        The study of nature is a large, if not the onl...
3        Although humans are part of nature, human acti...
4        [1] The word nature is borrowed from the Old F...
                               ...                        
10332    ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...
10333    ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...
10334    ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...
10335    ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...
10336    ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...
Name: Text, Length: 10337, dtype: object

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state= 42, stratify = y)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
cv = CountVectorizer()
model =MultinomialNB()
pipe = Pipeline([('vectorizer', cv), ('multinomialNB', model)])
pipe.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('multinomialNB', MultinomialNB())])

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred = pipe.predict(X_test)

ac =accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
print(ac, cm, cr)

0.9763056092843327 [[102   0   0   5   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  83   0   2   0   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0 106   3   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 276   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2 201   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   0  92   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   0   0  71   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  12   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   1   0   0   0 137   0   0   0   0   0   0   0   0]
 [  0   0   0   4   0   0   0   0   0  70   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0 118   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0   0 145   0   1   0   0   0]
 [  0   0   0   5   0   0   0   0   0   0   0   0 133   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0   0   0   0 162 

In [ ]:
#save and download the model
with open('trained_pipeline-0.1.0.pkl', 'wb') as f:
    pickle.dump(pipe, f)
    

In [16]:
#text = "Hola, como estas?"
text = "Ciao, come stai?"

y = model.predict(cv.transform([text]).toarray().reshape(1,-1))
le.classes_[y[0]], y

('Italian', array([8]))